OPTION(EXAMPLE "Run straight from the source" OFF)

IF (EXAMPLE)
    INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/src)
    LINK_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/src)

    ADD_EXECUTABLE(example example/Example.cpp)
    TARGET_LINK_LIBRARIES(example PRIVATE ${REQUIRED_LIBRARIES})
    TARGET_COMPILE_DEFINITIONS(example PRIVATE ${REQUIRED_DEFINITIONS})
ENDIF()