IF (NOT MYSQLCXX_DIR)
  MESSAGE("-- Setting default MySQL Directory")
  SET(MYSQLCXX_DIR "/usr/local/mysql-connector-c++")
ENDIF (NOT MYSQLCXX_DIR)

IF (NOT MYSQLCXX_INCLUDE_DIR)
  MESSAGE("-- Setting default MySQL Include Directory")
  SET(MYSQLCXX_INCLUDE_DIR "/usr/local/mysql-connector-c++/include")
ENDIF (NOT MYSQLCXX_INCLUDE_DIR)

MESSAGE("-- MYSQLCXX_LIB_DIR\t" ${MYSQLCXX_LIB_DIR})
MESSAGE("-- MYSQLCXX_INCLUDE_DIR" ${MYSQLCXX_INCLUDE_DIR})

INCLUDE_DIRECTORIES(${MYSQLCXX_INCLUDE_DIR})
LINK_DIRECTORIES(${MYSQLCXX_INCLUDE_DIR})
