IF (NOT HIREDIS_LIBRARIES)
  MESSAGE("-- Setting default Hiredis Library Directory")
  SET(HIREDIS_LIBRARIES "/usr/local/lib/libhiredis.a")
ENDIF (NOT HIREDIS_LIBRARIES)

MESSAGE("-- HIREDIS_LIBRARIES\t" ${HIREDIS_LIBRARIES})

IF (NOT HIREDIS_INCLUDE_DIRS)
  MESSAGE("-- Setting default Hiredis Include Directory")
  SET(HIREDIS_INCLUDE_DIRS "/usr/local/include/hiredis")
ENDIF (NOT HIREDIS_INCLUDE_DIRS)

MESSAGE("-- HIREDIS_INCLUDE_DIRS\t" ${HIREDIS_INCLUDE_DIRS})

INCLUDE_DIRECTORIES(${HIREDIS_INCLUDE_DIRS})
LINK_DIRECTORIES(${HIREDIS_INCLUDE_DIRS})

SET(
  REQUIRED_LIBRARIES
  ${REQUIRED_LIBRARIES}
  ${HIREDIS_LIBRARIES}
)
