IF (NOT WSSPP_INCLUDE_DIR)
  MESSAGE("-- Setting default Websocket++ Include Directory")
  SET(WSSPP_INCLUDE_DIR "/usr/local/include/websocketpp")
ENDIF (NOT WSSPP_INCLUDE_DIR)

MESSAGE("-- WSSPP_INCLUDE_DIR\t" ${WSSPP_INCLUDE_DIR})

INCLUDE_DIRECTORIES(${WSSPP_INCLUDE_DIR})
LINK_DIRECTORIES(${WSSPP_INCLUDE_DIR})
